[package]
name = "circuit_runner"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quizx = { path = "../quizx" }
num = "0.3.1"
rustc-hash = "1.1.0"
rayon = "1.5.0"
